### ISSUE TITLE
Need Help in using this project

### ISSUE THREAD

**Issue by AnilRahul** [apifest/apifest-oauth20#70]
I have a client Id and client secret for the app registered in facebook.
I am trying to make a post request to the server.
localhost:8087/oauth20/applications
with body : 

{
    "client_id" :"946272892035891679",
    "client_secret"  : "35e2e368234551019fb7bafeaa163a97920",
    "name":"test",
    "redirect_uri":"http://127.0.0.1:8087",
    "scope" :"basic"
    
}

i get the response as :
{
  "error": "scope does not exist"
}

Since i am relatively new to this oauth , I'm facing a difficulty to understand what scope is and what value it has to have.   can you please explain me how to go about. If any documentation of how to use to project would be helpful.

**Comment by rossitsaborissova** [comment]
Please, use the apifest mail group for any problems or questions you face/have - apifest@googlegroups.com. A full documentation is available on the apifest site - http://apifest.com.
About your current problem, you should first register the scope "basic" in order to register a client application with that scope.

**Comment by AnilRahul** [comment]
Thank you :) :) :+1:
